services:
  db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data